data_pth: ./
ckpt:
  caformer_s18: ./caformer/caformer_s18_384_in21ft1k.pth
  caformer_m36: ./caformer/caformer_m36_384_in21ft1k.pth
  caformer_b36: ./caformer/caformer_b36_384_in21ft1k.pth


train_cfg:
  stepsize: 3
  maxepoch: 50
  gpu: "0"
  output: Finder-train
  dataset: Finder
  encoder: DDN-M36
  batch_size: 16
  LR: 0.0001
  weight_decay: 0.0005
  kl_weight: !!float 1e-2
  sampling: 500
  start_epoch: 0
  print_freq: 1
  itersize: 1
  distribution: gs
  model: model.sigma_logit_unet
  mode: train
  note: default set of DDN, training on BSDS
  noise_rate: 0.3
  loss_lmbda: 1.1
